### ISSUE TITLE
Keep banning error.

### ISSUE THREAD

**Issue by avatar-lavventura** [StocksExchange/php-client#1]
I keep getting banned when I try to open `https://stocks.exchange/api2/prices` why?

**Comment by MaxPovver** [comment]
+1

**Comment by sevisilex** [comment]
I think you could only use it twice for every minute but I'm not sure because it works for me

**Comment by vans163** [comment]
They should really lift the limits for API requests under authentication. Its WAY too low, something like 1 request per minute.

**Comment by Drengel1990** [comment]
@avatar-lavventura 
Good day
We updated our api
Fixed many bugs
Please try a new API
