### ISSUE TITLE
The refresh token is invalid.

### ISSUE THREAD

**Issue by Hannibal65** [StocksExchange/php-client#11]
I am  trying to use PHP API V3, but when i want to make a private call,  like 
$se->profileInfo();
 it returns error:
Fatal error:  Uncaught Error: Client error: `POST https://api3.stex.com/oauth/token` resulted in a `401 Unauthorized` response:
{"error":"invalid_request","error_description":"The refresh token is invalid.","hint":"Cannot decrypt the refresh token" (truncated...)
 in stocks_exchange\php-client\src\ApiVersion\Three.php:471

**Comment by Drengel1990** [comment]
Which do you use scope?

**Comment by Drengel1990** [comment]
Need use scope profile

**Comment by Drengel1990** [comment]
Maybe your refresh_token is expire?
