### ISSUE TITLE
Private API doesn't work, Cloudflare problem?

### ISSUE THREAD

**Issue by SplendidGoT** [StocksExchange/php-client#2]
The public API works flawless, but the private API doesn't return any data. It looks it's because of Cloudflare, I'm only getting return data from Cloudflare.

I'm I doing something wrong or is there really a problem with the private API?

Thank you in advance!

**Comment by flyneko** [comment]
Did you solve the problem? There is still a problem with the Cloudflare

**Comment by SplendidGoT** [comment]
No, still the same problem :(

**Comment by MaxPovver** [comment]
@SplendidGoT did you try to change url from 'https://stocks.exchange/api2' to 'https://stocks.exchange/api2/' ? Worked for me

**Comment by SplendidGoT** [comment]
I did, I'm getting once in a while some data, but 9 out of 10, no response. Really buggy, can't use it at all this way.
