### ISSUE TITLE
Uncaught Error: Class 'ApiController' not found

### ISSUE THREAD

**Issue by MetallianFR68** [StocksExchange/php-client#4]
Hi
The STOCKEXCHANGE PHP CLASS calls a class called ApiController
$client = new ApiController();

I get an error :  Uncaught Error: Class 'ApiController' not found

Where am I supposed to find ApiController() ?

Did I miss something ?

**Comment by darkmaycal** [comment]
+

**Comment by Drengel1990** [comment]
@MetallianFR68 
Good day
We updated our api
Fixed many bugs
Please try a new API
