### ISSUE TITLE
No fees, for some trades no timestamp is returned. Method TradeHistory

### ISSUE THREAD

**Issue by MaxPovver** [StocksExchange/php-client#6]
Hello
According to docs:
_5. Trade History_
_Get information about all closed orders. Return an overview of:_

_1.     order id (order id in database)_

_2.    pair (currency pair contained in order record)_

_3.    type (order type: buy or sell)_

_4.    amount (the amount that remains to implement)_

_5.    rate (order price)_

_6.    order indicate (indicates that your order or not)_

_7.    timestamp (order creation time)_

**_8.   fee (order operation fee)_**

**_9.  currency_fee (currency fee code_**

In fact, you never return fee info. And sometimes you return false instead of timestamp. Here is example:
"data":{"2525410":{"pair":"BWK_BTC","type":"sell","buy_amount":"0.00081418216068","sell_amount":"3.804234","rate":"0.00021402","is_your_order":0,"timestamp":false},"2325797":{"pair":"ITL_BTC","type":"sell","buy_amount":"0.0135","sell_amount":"1350000","rate":"1e-08","is_your_order":0,"timestamp":false},"2394940":{"pair":"VTAR_BTC","type":"sell","buy_amount":"0.00199398","sell_amount":"501","rate":"3.98e-06","is_your_order":0,"timestamp":false},"5109118":{"pair":"ABS_BTC","type":"buy","buy_amount":"0.1","sell_amount":"1.89e-07","rate":"1.89e-06","is_your_order":0,"timestamp":1525930701},"5108453":{"pair":"BTCZ_BTC","type":"sell","buy_amount":"622.904595093458","sell_amount":"542.095812656542","rate":"3.5e-07","is_your_order":0,"timestamp":1525930679}
**Can you please fix that?**

**Comment by Drengel1990** [comment]
@MaxPovver as you can se there is a "type" parameter. The buy_amount is named wrongly, but it is too late to change the name to just "amount" as this API is already in use by a lot of applications. In version 3 this will be fixed
