### ISSUE TITLE
Wrong naming for buy and sell amount

### ISSUE THREAD

**Issue by MaxPovver** [StocksExchange/php-client#7]
"5109053":{"pair":"RBMC_BTC","type":"buy","buy_amount":"0.00034928","sell_amount":"472","rate":"7.4e-07","is_your_order":0,"timestamp":1525930616},"5109098":{"pair":"RBMC_BTC","type":"sell","buy_amount":"0.00034928","sell_amount":"472","rate":"7.4e-07","is_your_order":0,"timestamp":1525930616}

In one of these trades returned by your api RBMC was bought, in another - sold. But in both RMBC is returned as sell amount. Please fix that.

**Comment by Drengel1990** [comment]
@MaxPovver as you can se there is a "type" parameter. The buy_amount is named wrongly, but it is too late to change the name to just "amount" as this API is already in use by a lot of applications. In version 3 this will be fixed
