### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by woodsbox** [StocksExchange/php-client#8]
I'm a bit new to github, what is the best way to install this on Apache2 on Ubuntu 16.04?

**Comment by Drengel1990** [comment]
Hello!
First need install Composer
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-16-04
Second need run command in folder project 
`composer install`
And the end please reed https://github.com/StocksExchange/php-client#example

**Comment by woodsbox** [comment]
Second need run command in folder project
composer install

Do I need to put StocksExchange behind the composer install like:

`composer install StocksExchange`
